### ISSUE TITLE
Installation on mac, ERROR: No matching distribution found for pywin32

### ISSUE THREAD

**Issue by RSChegani** [PALMS-gui/PALMS#1]
I followed the steps to install the requirements, but it looks like one of them is pywin32, which can't be installed on mace
```
% pip install pywin32
ERROR: Could not find a version that satisfies the requirement pywin32
ERROR: No matching distribution found for pywin32
```
Is this module absolutely necessary? 

I have python3.6 and macOS 11.0.1

When I ignore pywin32 and install the rest I get the following error:
```
 % python __main__.py
Traceback (most recent call last):
  File "__main__.py", line 20, in <module>
    from gui import PALMS
  File "/Users/rana_chegani/repos/PALMS/gui/__init__.py", line 1, in <module>
    from . import display_panel, model, plot_area, rendering,\
  File "/Users/rana_chegani/repos/PALMS/gui/display_panel.py", line 11, in <module>
    from .plot_area import PlotArea
  File "/Users/rana_chegani/repos/PALMS/gui/plot_area.py", line 20, in <module>
    from logic.databases.DatabaseHandler import Database
  File "/Users/rana_chegani/repos/PALMS/logic/databases/__init__.py", line 5, in <module>
    from logic.databases import DatabaseHandler
  File "/Users/rana_chegani/repos/PALMS/logic/databases/DatabaseHandler.py", line 24, in <module>
    from logic.operation_mode.partitioning import Partitions
  File "/Users/rana_chegani/repos/PALMS/logic/operation_mode/partitioning.py", line 13, in <module>
    import win32com
ModuleNotFoundError: No module named 'win32com'
```

**Comment by PALMS-gui** [comment]
Not surprising, that pywin32 package does not exist for Mac. 
I think it is used to communicate with Excel application in the event of certain error (if not possible to write into file, because the file is open, then close the file). If you look and comment all lines mentioning 'win32com' (4 import statements and 3 usages), it should be possible to avoid this particular dependency, but, more generally, PALMS was never tested for other OS, except Windows 10, so I can not say which other issues might appear.

https://ibb.co/whCHZp8 screenshot

**Comment by PALMS-gui** [comment]
@RSChegani please let us know whether you succeeded running PALMS on Mac.

**Comment by RSChegani** [comment]
> @RSChegani please let us know whether you succeeded running PALMS on Mac.

I ran it on Mac, there was a couple of the libraries that I had to update to the latest version, instead of the version listed in requirements.txt, and I had to remove  `pywin32` from both requirements.txt and the code, then I was able to run it
